### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by zxp19821005** [seita1996/frontimer#70]
I've ported the package to AUR , and it run well on my EndeavourOS . You can see it from https://aur.archlinux.org/packages/frontimer .
I've some suggestions:
### package.json
Will you please add a new line in `scripts` section as below ?
```
"ebuilder:linux": "electron-builder --linux AppImage",
```
### Taskbar icon
When I run the program , I can't see the icon of the program , instead of that it was just and unknown icon . Will you please fix it ?

**Comment by seita1996** [comment]
@zxp19821005 

Fixes have been completed.
I have confirmed that the icon can be displayed on my Ubuntu.

![image](https://github.com/seita1996/frontimer/assets/19267892/81a2da87-79d4-467c-94ea-e37fc3a60e62)

Please download AppImage from [the latest release](https://github.com/seita1996/frontimer/releases/tag/v0.1.17)!

**Comment by zxp19821005** [comment]
OK,thank you!
